name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      id: ${{ steps.create_release.outputs.id }}

  build-client:
    runs-on: ubuntu-latest
    needs: create-release
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build NDS Client
        working-directory: client/nds
        run: make

      - name: Build 3DS Client
        working-directory: client/3ds
        run: make

      - name: Upload NDS Client Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: client/nds/client.nds
          asset_name: client.nds
          asset_content_type: application/octet-stream

      - name: Upload 3DS Client Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: client/3ds/client.3dsx
          asset_name: client.3dsx
          asset_content_type: application/octet-stream


  build-server:
    runs-on: ubuntu-latest
    needs: create-release
    container:
      image: golang:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Server
        working-directory: server
        run: make build

      - name: Upload Server Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: server/server
          asset_name: server
          asset_content_type: application/octet-stream

