name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make g++
          wget https://github.com/devkitPro/pacman/releases/latest/download/devkitpro-pacman.deb
          sudo dpkg -i devkitpro-pacman.deb
          sudo dkp-pacman -Syu --noconfirm
          sudo dkp-pacman -S nds-dev --noconfirm

      - name: Build for Linux
        working-directory: client
        run: make build-linux

      - name: Build default target
        working-directory: client
        run: make

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            client/client.nds
            client/client
